<?php

define('TODOLIST', true);
define('TODO_SET_STATUS_ON_CREATE', true);
define('TODO_COMMENTS_ENABLE', true);
define('TODO_PROGRESS_ENABLE', false);
define('TODO_ENABLE_STATS', true);
define('TODO_TODOS_PER_PAGE', 25);
define('TODO_DEFAULT_SORT_FIELD', 'statusID');
define('TODO_DEFAULT_SORT_ORDER', 'ASC');
define('TODO_UNSOLVED_WARNING', true);
define('TODO_UNSOLVED_WARNING_TIME', 14);
define('TODO_UNSOLVED_WARNING_HIDE_DURATION', 168);
define('TODO_OVERDUE_WARNING', true);
define('TODO_OVERDUE_WARNING_HIDE_DURATION', 48);
define('TODO_WAITING_WARNING', true);
define('TODO_WAITING_WARNING_HIDE_DURATION', 48);
